[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["ja"]}

[dev]
  command = "python3 -m http.server 3000"
  port = 3000
  publish = "."
